### ISSUE TITLE
Password Param or No Password Supplied Error

### ISSUE THREAD

**Issue by cleibl** [rcleveng/django_gcp_iam_auth#2]
Hi @rcleveng - 

I found this package through this issue https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/issues/437 and was trying it out.

I followed the docs but didn't see where I was supposed to specify the DB User and DB Name so I added those into the Databases dict in settings.py as show below:

```python
DATABASES = {
    'default': {
        'ENGINE': 'django_gcp_iam_auth.postgresql',
        'NAME': env.get('POSTGRESQL_NAME'),
        'USER': env.get('POSTGRESQL_USER'),
         # I've tried with password commented out as well
        'PASSWORD': 'password'
        'HOST': env.get('POSTGRESQL_HOST'),
    }
}
```

When I add the 'PASSWORD' Param I get a 

```
Cloud SQL IAM service account authentication failed for user `<my-sa@myproject.gserviceaccount.iam`.
```

This makes me believe it is using the "password" I supplied in the dictionary params and not the token.  When I don't add the 'PASSWORD' param I get 

```
connection failed: connection to server on socket "/cloudsql/{db_connection_string}/.s.PGSQL.5432" failed: fe_sendauth: no password supplied
```

We are using Cloud SQL Postgres and the following package versions.

From `pip list`

```shell
Django                                5.0.6
django_gcp_iam_auth                   0.0.4
```

Any Suggestions?

**Comment by rcleveng** [comment]
Hey there, looks like I missed one piece of the instructions which was added as a secondary check.   Under the 'default' block, add a 'gcp_iam_auth' = True to the 'OPTIONS' dict.  I do it optionally in my settings.py depending on if I'm talking to a local test database or production one using iam auth.

Here's what I'm using:
```
DATABASES["default"]["OPTIONS"]["gcp_iam_auth"] = (GCP_IAM_AUTH,)
```

Actually the full block (if it's helpful):

```
# Database
# https://docs.djangoproject.com/en/stable/ref/settings/#databases

GCP_IAM_AUTH = env.bool("GCP_IAM_AUTH", default=False)

# Enable connection pooling for up to 2m
CONN_MAX_AGE = 2 * 60

if GCP_IAM_AUTH:
    import django_gcp_iam_auth.postgresql

    print(f'Using GCP IAM Database Authentication to "{DATABASES["default"]["HOST"]}:{DATABASES["default"]["PORT"]}')
    print(f"{DATABASES}")
    DATABASES["default"]["ENGINE"] = ("django_gcp_iam_auth.postgresql",)
    DATABASES["default"]["OPTIONS"]["gcp_iam_auth"] = (GCP_IAM_AUTH,)
else:
    print(f'Using Database: "{DATABASES["default"]["HOST"]}"')

```

**Comment by cleibl** [comment]
Yes that was the issue! Thank you.  

I should have reviewed the Wrapper more closely and would have seen it was looking for that param.

**Comment by rcleveng** [comment]
Awesome, glad to hear it!
